spring.application.name=gateway

#identity
spring.cloud.gateway.server.webmvc.routes[0].id=identity
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://IDENTITY
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/auth/**

eureka.client.service-url.defaultZone=http://localhost:8081/eureka

server.port=8080


eureka.client.registry-fetch-interval-seconds=5